### ISSUE TITLE
UI framework built from scratch in C

### ISSUE THREAD

**Issue by srevrtt** [srevrtt/mcmapper#1]
**Description**
MCMapper will be a GUI application, meaning graphics would need to be displayed. MCMapper will use C and OpenGL to create a GUI framework from scratch to provide the maximum performance for its users. At the beginning of its development, it will use GLFW for window creation until it is ready for a custom window creator. This is the main issue containing all of the tasks. But, each task has its own issue.

**Tasks**

- [ ] GLFW window creation
- [ ] OpenGL rendering setup
- [ ] Rectangle component
- [ ] Image component
- [ ] Text component
- [ ] Button component
- [ ] Slider component
- [ ] TextInput component
- [ ] RichTextInput component
- [ ] Window creation without GLFW
- [ ] More polished event system
